# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Automation Pipeline

on:
  push:
    branches: [ master, DEV-MASTER]
  pull_request:
    branches: [ master, DEV-MASTER]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - name: Checkout actions code
      uses: actions/checkout@v2
    - name: Use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run build
      run: npm run build --if-present
    - name: Lint files
      run: npm run lint
    - name: Run tests
      run: npm test
    - name: Run test coverage
      run: npm run code-coverage-check
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: npm test
        debug: true