name: Selenium Java CI
on:
  pull_request:
    branches: [master, DEV-MASTER]

jobs:
  build:
    runs-on: ubuntu-latest # Using linux machine
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    - name: Checkout qa repo
      uses: actions/checkout@v2
      with:
        repository: cse112-sp20/calamari-qa
        path: qa
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1 # Setup JAVA
      with:
        java-version: 1.12
    - name: Use node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install node dependencies
      run: |
        cd main
        npm ci
    - name: Run token script
      run: |
        cd qa
        chmod +x InsertToken.sh
        ./InsertToken.sh
      env:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
    - name: Create crx file
      run: |
        cd main
        npm run chrome-ext
    - name: Move CRX file
      run: |
        cd qa
        rm ./ui/src/main/resources/extensions/*.crx
        mv ./../main/web-extension.crx ./ui/src/main/resources/extensions/velocity_raptor.crx
    - name: Run Selenium Tests
      run: | 
        cd qa
        xvfb-run mvn clean test # Run our tests using Maven